### ISSUE TITLE
Создание новой темы в админ. панели

### ISSUE THREAD

**Issue by iTechMedia** [artdevue/modxTalks#36]
Удалил существующую тему с демо-комментом (1шт), коммент остался, тема удалена, не могу создать тему заново для новых комментариев...
Что я делаю не так?:)

**Comment by iTechMedia** [comment]
Почистил кеш - все стало ок.
Классно я сегодня сам вопросы задаю - сам решаю....

**Comment by artdevue** [comment]
гы... :)
