### ISSUE TITLE
Не собирается пакет с гит

### ISSUE THREAD

**Issue by arimanr** [artdevue/modxTalks#41]
Как я вижу, компонент развивается и это радует, но собрать пакет после скачивания архива отсюда не получилось. Использую пререлизную modx 2.5.0rc1, но со сборкой других компонентов проблем не возникало. PHP 5.4 При активации скрипта build.transport.php пишет 

> Ошибка при загрузке http://sitena.me/modxTalks-master/_build/build.transport.php. Возможно, на сайте ведутся работы или он настроен неправильно.

При этом в официальном репозитории висит версия 2013 года да еще с пометкой "бета". Обновите, пожалуйста modxTalk в репозитории или укажите где, что поправить, чтобы пакет начал собираться из архива гитхаб.

**Comment by vanchelo** [comment]
Поправим
