### ISSUE TITLE
Не работает сортировка по колличеству комментариев в админке((

### ISSUE THREAD

**Issue by manicko** [artdevue/modxTalks#7]
Сортировка в админке работает по названию темы, но не активна по количеству комментариев.

![untitled](https://f.cloud.github.com/assets/1097057/1107241/2ac15292-1959-11e3-9f06-a81b8ed809e8.jpg)

Подскажите, в чем может быть проблема?

**Comment by vanchelo** [comment]
Для реализации требуемого функционала придется изменять структуру таблиц в базе данных. У меня давно в другой ветке внесены эти изменения, но в основную ветку я пока не добавил этот функционал
