### ISSUE TITLE
Проблемы совместимости с ajaxManager

### ISSUE THREAD

**Issue by Drakon5999** [artdevue/modxTalks#9]
Попробовал установить данное дополнение, но из за несовместимости с дополнением ajaxManager, не смог им воспользоваться...

**Comment by vanchelo** [comment]
Уже совместимо, добавьте в системную настройку `ajaxmanager.compatible_namespaces` -> `modxtalks` чтобы получилось примерно так 
```
core,clientconfig,minishop2,resourcehider,gallery,modxtalks
```
